system(['make EXTERN_DEFS="-DMATLAB -I/usr/local/matlab75/extern/include" ' ...
        '-C ../cc sylvester.a'])
mex gensylv.cpp -I../cc -DMATLAB ../cc/sylvester.a ...
    /usr/local/matlab75/bin/glnxa64/libmwlapack.so ...
    /usr/local/matlab75/bin/glnxa64/libmwblas.so

