function mhname = get_name_of_the_last_mh_file(M_)
% part of DYNARE, copyright Dynare Team (2008)
% Gnu Public License.
    model_name = M_.fname ;
    mcmc_directory = M_.dname ;
    load([ mcmc_directory '/metropolis/' model_name '_mh_history']) ;
    mh_number = record.LastFileNumber ;
    bk_number = record.Nblck ;
    clear('record') ;
    mhname = [ mcmc_directory ...
               '/metropolis/' ...
               model_name ...
               '_mh' ...
               int2str(mh_number) ...
               '_blck' ...
               int2str(bk_number) ...
               '.mat'] ;