Description of CheckPath
Home > . > CheckPath.m
CheckPath
PURPOSE
06-03-2005
SYNOPSIS
function DirectoryName = CheckPath(type)
DESCRIPTION
 06-03-2005
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CutSample stephane.adjemian@ens.fr [09-09-2005]
GetAllPosteriorDraws stephane.adjemian@ens.fr [09-09-2005]
GetPosteriorParametersStatistics stephane.adjemian@ens.fr [09-09-2005]
McMCDiagnostics stephane.adjemian@ens.fr [06-04-2005]
PlotPosteriorDistributions stephane.adjemian@ens.fr [09-09-2005]
PosteriorIRF stephane.adjemian@ens.fr [09-25-2005]
PosteriorSmoother stephane.adjemian@ens.fr [09-25-2005]
ReshapeMatFiles Reshape and sort (along the mcmc simulations) the mat files generated
dynare_estimation
dynare_sensitivity copyright Marco Ratto 2006
filt_mc_ copyright Marco Ratto 2006
marginal_density stephane.adjemian@ens.fr [09-09-2005]
metropolis stephane.adjemian@ens.fr [09-02-2005]
metropolis_draw
SOURCE CODE
function DirectoryName = CheckPath(type)
% 06-03-2005
global M_
DirectoryName = [ M_.dname '/' type ];
if ~isdir(DirectoryName)
    mkdir('.',DirectoryName);
end