Description of dynare_resolve
Home > . > dynare_resolve.m
dynare_resolve
PURPOSE
SYNOPSIS
function [A,B,ys,info] = dynare_resolve()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
kalman_transition_matrix makes transition matrices out of ghx and ghu for Kalman filter
resol Copyright (C) 2001 Michel Juillard
This function is called by:
DsgeLikelihood stephane.adjemian@cepremap.cnrs.fr [09-07-2004]
DsgeSmoother stephane.adjemian@cepremap.cnrs.fr [09-07-2004]
SOURCE CODE
function [A,B,ys,info] = dynare_resolve()
  global oo_
  [oo_.dr,info] = resol(oo_.steady_state,0);
  if info(1) > 0
    A = [];
    B = [];
    ys = [];
    return
  end
  [A,B] = kalman_transition_matrix(oo_.dr);
  ys = oo_.dr.ys;