Description of GetOneDraw
Home > . > GetOneDraw.m
GetOneDraw
PURPOSE
stephane.adjemian@ens.fr [09-25-2005]
SYNOPSIS
function [xparams, logpost] = GetOneDraw(type)
DESCRIPTION
 stephane.adjemian@ens.fr [09-25-2005]
CROSS-REFERENCE INFORMATION
This function calls:
metropolis_draw
This function is called by:
PosteriorIRF stephane.adjemian@ens.fr [09-25-2005]
PosteriorSmoother stephane.adjemian@ens.fr [09-25-2005]
SOURCE CODE
function [xparams, logpost] = GetOneDraw(type)
% stephane.adjemian@ens.fr [09-25-2005]
  switch type
   case 'posterior'
    [xparams, logpost] = metropolis_draw(0);
   case 'prior'
    xparams = prior_draw(0);
  end