Description of lpdfgam
Home > . > lpdfgam.m
lpdfgam
PURPOSE
log GAMMA PDF
SYNOPSIS
function ldens = lpdfgam(x,a,b);
DESCRIPTION
 log GAMMA PDF
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
compDist
draw_prior_density stephane.adjemian@ens.fr [07-15-2004]
mj_qgamma MJ_QGAMMA The gamma inverse distribution function
priordens This procedure computes a prior density for
SOURCE CODE
function  ldens = lpdfgam(x,a,b);
% log GAMMA PDF
  ldens = -gammaln(a) -a*log(b)+ (a-1)*log(x) -x/b ;
% 10/11/03  MJ adapted from an earlier GAUSS version by F. Schorfeide,
%              translated to MATLAB by R. Wouters
%              use MATLAB gammaln rather than lngam