Description of pgamma
Home > . > pgamma.m
pgamma
PURPOSE
PGAMMA The gamma distribution function
SYNOPSIS
function F = pgamma(x,a)
DESCRIPTION
PGAMMA   The gamma distribution function
         F = pgamma(x,a)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fgamma
figamm
mj_qgamma MJ_QGAMMA The gamma inverse distribution function
qgamma QGAMMA The gamma inverse distribution function
SOURCE CODE
function F = pgamma(x,a)
%PGAMMA   The gamma distribution function
%
%         F = pgamma(x,a)
%       Anders Holtsberg, 18-11-93
%       Copyright (c) Anders Holtsberg
if any(any(a<=0))
   error('Parameter a is wrong')
end
F = gammainc(x,a);
I0 = find(x<0);
F(I0) = zeros(size(I0));