Description of qzdiv
Home > . > qzdiv.m
qzdiv
PURPOSE
from Chris Sims web site
SYNOPSIS
function [A,B,Q,Z] = qzdiv(stake,A,B,Q,Z)
DESCRIPTION
 from Chris Sims web site
 http://eco-072399b.princeton.edu/yftp/gensys/mfiles/QZDIV.M
CROSS-REFERENCE INFORMATION
This function calls:
qzswitch from Chris Sims web site
This function is called by:
dr1 Copyright (C) 2001 Michel Juillard
dr11 Copyright (C) 2001 Michel Juillard
SOURCE CODE
% from Chris Sims web site
% http://eco-072399b.princeton.edu/yftp/gensys/mfiles/QZDIV.M
%
function [A,B,Q,Z] = qzdiv(stake,A,B,Q,Z)
%function [A,B,Q,Z] = qzdiv(stake,A,B,Q,Z)
%
% Takes U.T. matrices A, B, orthonormal matrices Q,Z, rearranges them
% so that all cases of abs(B(i,i)/A(i,i))>stake are in lower right
% corner, while preserving U.T. and orthonormal properties and Q'AZ' and
% Q'BZ'.
%
[n jnk] = size(A);
root = abs([diag(A) diag(B)]);
root(:,1) = root(:,1)-(root(:,1)<1.e-13).*(root(:,1)+root(:,2));
root(:,2) = root(:,2)./root(:,1);
for i = n:-1:1
   m=0;
   for j=i:-1:1
      if (root(j,2) > stake | root(j,2) < -.1)
         m=j;
         break
      end
   end
   if (m==0)
      return
   end
   for k=m:1:i-1
      [A B Q Z] = qzswitch(k,A,B,Q,Z);
      tmp = root(k,2);
      root(k,2) = root(k+1,2);
      root(k+1,2) = tmp;
   end
end