Description of selif
Home > . > selif.m
selif
PURPOSE
Copyright (C) 2001 Michel Juillard
SYNOPSIS
function x = selif(a,b)
DESCRIPTION
 Copyright (C) 2001 Michel Juillard
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bksup Copyright (C) 2001 Michel Juillard
bksupk
simk Copyright (C) 2001 Michel Juillard
SOURCE CODE
% Copyright (C) 2001 Michel Juillard
%
function x = selif(a,b)
if size(b,2) ~= 1
    error ('The second argument in SELIF must be  column vector') ;
end
x = a(find(b == 1),:) ;
return ;