Description of set_default_option
Home > . > set_default_option.m
set_default_option
PURPOSE
SYNOPSIS
function options=set_default_option(options,field,default)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
check Copyright (C) 2001 Michel Juillard
disp_moments Copyright (C) 2001 Michel Juillard
dr1 Copyright (C) 2001 Michel Juillard
dr11 Copyright (C) 2001 Michel Juillard
dynare_MC
dynare_estimation
dynare_sensitivity copyright Marco Ratto 2006
dynare_solve Copyright (C) 2001 Michel Juillard
make_ex_ Copyright (C) 2001 Michel Juillard
make_y_ Copyright (C) 2001 Michel Juillard
olr Copyright (C) 2001 Michel Juillard
osr Copyright (C) 2001 Michel Juillard
print_info Copyright (C) 2005 Michel Juillard
resol Copyright (C) 2001 Michel Juillard
simul Copyright (C) 2001 Michel Juillard
simult_ Copyright (C) 2001 Michel Juillard
steady Copyright (C) 2001 Michel Juillard
stoch_simul Copyright (C) 2001 Michel Juillard
SOURCE CODE
function options=set_default_option(options,field,default)
  if ~isfield(options,field)
    if sscanf(version('-release'),'%d') < 13
      options = setfield(options,field,default);
    else
      eval('options.(field) = default;');
    end
  end
  % 06/07/03 MJ added ; to eval expression