Description of union
Home > . > union.m
union
PURPOSE
SYNOPSIS
function x = union(a,b)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
calib
dynare_estimation
olr2 Copyright (C) 2003 Michel Juillard
set_state_space Copyright (C) 2001 Michel Juillard
simk Copyright (C) 2001 Michel Juillard
SOURCE CODE
function x = union(a,b)
xx = sort([a;b]) ;
x(1) = xx(1) ;
for i = 2:size(xx,1)
    if xx(i) ~= xx(i-1)
        x =[x;xx(i)];
    end
end
return ;