function [idemodel, idemoments] = mc_getJ(lpmat, M_,oo_,options_,0,indx,indexo,mf2,nlags,useautocorr);

for j=1:size(lpmat,1),
set_parameters(lpmat(j,:));
[JJ, H] = getJJ(M_,oo_,options_,0,indx,indexo,mf2,nlags,useautocorr);
    [idemodel.Mco(:,iteration), idemoments.Mco(:,iteration), ...
      idemodel.Pco(:,:,iteration), idemoments.Pco(:,:,iteration), ...
      idemodel.cond(iteration), idemoments.cond(iteration), ...
      idemodel.ee(:,iteration), idemoments.ee(:,iteration), ...
      idemodel.ind(:,iteration), idemoments.ind(:,iteration), ...
      idemodel.indno{iteration}, idemoments.indno{iteration}] = ...
      identification_checks(H,JJ);   
% [indok, indno, indweak] = dynare_identification(H,JJ);
end
